version: '2'

services:
  mssql:
    image: microsoft/mssql-server-linux
    ports:
      - "1433:1433"
    volumes:
      - mssqlvolume:/var/opt/mssql
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'P@55w0rd'

volumes:
  mssqlvolume:
    driver: local

